## Q - 1

In [1]:
import numpy as np

In [2]:
arr = np.arange(2,50,3)
print(arr)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


## Q - 2

In [4]:
list1 = []
list2 = []

for i in range(5):
  x = int(input(""))
  list1.append(x)

for i in range(5):
  x = int(input(""))
  list2.append(x)

arr1 = np.array(list1)
arr2 = np.array(list2)

con = np.concatenate((arr1, arr2))
print(con)

sortArr = np.sort(arr)
print(sortArr)

5
6
8
3
9
5
7
6
2
4
[5 6 8 3 9 5 7 6 2 4]
[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


## Q - 3

In [5]:
arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
print("Dimensions of array : ", arr.ndim)
print("Size of array : ", arr.size)

Dimensions of array :  2
Size of array :  9


## Q - 4

In [6]:
arr =  np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
print("Shape of 1d array :",arr.shape)
row = np.expand_dims(arr, axis=0)
print("Shape of 2d Array in row major :",row.shape)
col = np.expand_dims(arr, axis=1)
print("Shape of 2d Array in column major :",col.shape)

Shape of 1d array : (3, 3)
Shape of 2d Array in row major : (1, 3, 3)
Shape of 2d Array in column major : (3, 1, 3)


## Q - 5

In [7]:
arr1 = np.array([[1, 2], 
              [4, 3]]) 
  
arr2 = np.array([[5, 6], 
              [8, 7]]) 

print("Vertical stacking:", np.vstack((arr1, arr2)))
print("Horizontal stacking:", np.hstack((arr1, arr2)))

Vertical stacking: [[1 2]
 [4 3]
 [5 6]
 [8 7]]
Horizontal stacking: [[1 2 5 6]
 [4 3 8 7]]


## Q -6

In [9]:
a = np.array([1,2,3,5,6,8,2,2,4,5,1,3,6,4])
unique, counts = np.unique(a,return_counts=True)
print(np.asarray((unique, counts)).T)

[[1 2]
 [2 3]
 [3 2]
 [4 2]
 [5 2]
 [6 2]
 [8 1]]
